// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="pynq_sample_func,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=17.500000,HLS_SYN_LAT=11,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=765,HLS_SYN_LUT=888,HLS_VERSION=2020_1}" *)

module pynq_sample_func (
        ap_clk,
        ap_rst_n,
        sample_in,
        sample_out,
        m_axi_extMemPtr_V_AWVALID,
        m_axi_extMemPtr_V_AWREADY,
        m_axi_extMemPtr_V_AWADDR,
        m_axi_extMemPtr_V_AWID,
        m_axi_extMemPtr_V_AWLEN,
        m_axi_extMemPtr_V_AWSIZE,
        m_axi_extMemPtr_V_AWBURST,
        m_axi_extMemPtr_V_AWLOCK,
        m_axi_extMemPtr_V_AWCACHE,
        m_axi_extMemPtr_V_AWPROT,
        m_axi_extMemPtr_V_AWQOS,
        m_axi_extMemPtr_V_AWREGION,
        m_axi_extMemPtr_V_AWUSER,
        m_axi_extMemPtr_V_WVALID,
        m_axi_extMemPtr_V_WREADY,
        m_axi_extMemPtr_V_WDATA,
        m_axi_extMemPtr_V_WSTRB,
        m_axi_extMemPtr_V_WLAST,
        m_axi_extMemPtr_V_WID,
        m_axi_extMemPtr_V_WUSER,
        m_axi_extMemPtr_V_ARVALID,
        m_axi_extMemPtr_V_ARREADY,
        m_axi_extMemPtr_V_ARADDR,
        m_axi_extMemPtr_V_ARID,
        m_axi_extMemPtr_V_ARLEN,
        m_axi_extMemPtr_V_ARSIZE,
        m_axi_extMemPtr_V_ARBURST,
        m_axi_extMemPtr_V_ARLOCK,
        m_axi_extMemPtr_V_ARCACHE,
        m_axi_extMemPtr_V_ARPROT,
        m_axi_extMemPtr_V_ARQOS,
        m_axi_extMemPtr_V_ARREGION,
        m_axi_extMemPtr_V_ARUSER,
        m_axi_extMemPtr_V_RVALID,
        m_axi_extMemPtr_V_RREADY,
        m_axi_extMemPtr_V_RDATA,
        m_axi_extMemPtr_V_RLAST,
        m_axi_extMemPtr_V_RID,
        m_axi_extMemPtr_V_RUSER,
        m_axi_extMemPtr_V_RRESP,
        m_axi_extMemPtr_V_BVALID,
        m_axi_extMemPtr_V_BREADY,
        m_axi_extMemPtr_V_BRESP,
        m_axi_extMemPtr_V_BID,
        m_axi_extMemPtr_V_BUSER,
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_state2 = 12'd2;
parameter    ap_ST_fsm_state3 = 12'd4;
parameter    ap_ST_fsm_state4 = 12'd8;
parameter    ap_ST_fsm_state5 = 12'd16;
parameter    ap_ST_fsm_state6 = 12'd32;
parameter    ap_ST_fsm_state7 = 12'd64;
parameter    ap_ST_fsm_state8 = 12'd128;
parameter    ap_ST_fsm_state9 = 12'd256;
parameter    ap_ST_fsm_state10 = 12'd512;
parameter    ap_ST_fsm_state11 = 12'd1024;
parameter    ap_ST_fsm_state12 = 12'd2048;
parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_EXTMEMPTR_V_ID_WIDTH = 1;
parameter    C_M_AXI_EXTMEMPTR_V_ADDR_WIDTH = 32;
parameter    C_M_AXI_EXTMEMPTR_V_DATA_WIDTH = 32;
parameter    C_M_AXI_EXTMEMPTR_V_AWUSER_WIDTH = 1;
parameter    C_M_AXI_EXTMEMPTR_V_ARUSER_WIDTH = 1;
parameter    C_M_AXI_EXTMEMPTR_V_WUSER_WIDTH = 1;
parameter    C_M_AXI_EXTMEMPTR_V_RUSER_WIDTH = 1;
parameter    C_M_AXI_EXTMEMPTR_V_BUSER_WIDTH = 1;
parameter    C_M_AXI_EXTMEMPTR_V_TARGET_ADDR = 0;
parameter    C_M_AXI_EXTMEMPTR_V_USER_VALUE = 0;
parameter    C_M_AXI_EXTMEMPTR_V_PROT_VALUE = 0;
parameter    C_M_AXI_EXTMEMPTR_V_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_AXILITES_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_EXTMEMPTR_V_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   sample_in;
output   sample_out;
output   m_axi_extMemPtr_V_AWVALID;
input   m_axi_extMemPtr_V_AWREADY;
output  [C_M_AXI_EXTMEMPTR_V_ADDR_WIDTH - 1:0] m_axi_extMemPtr_V_AWADDR;
output  [C_M_AXI_EXTMEMPTR_V_ID_WIDTH - 1:0] m_axi_extMemPtr_V_AWID;
output  [7:0] m_axi_extMemPtr_V_AWLEN;
output  [2:0] m_axi_extMemPtr_V_AWSIZE;
output  [1:0] m_axi_extMemPtr_V_AWBURST;
output  [1:0] m_axi_extMemPtr_V_AWLOCK;
output  [3:0] m_axi_extMemPtr_V_AWCACHE;
output  [2:0] m_axi_extMemPtr_V_AWPROT;
output  [3:0] m_axi_extMemPtr_V_AWQOS;
output  [3:0] m_axi_extMemPtr_V_AWREGION;
output  [C_M_AXI_EXTMEMPTR_V_AWUSER_WIDTH - 1:0] m_axi_extMemPtr_V_AWUSER;
output   m_axi_extMemPtr_V_WVALID;
input   m_axi_extMemPtr_V_WREADY;
output  [C_M_AXI_EXTMEMPTR_V_DATA_WIDTH - 1:0] m_axi_extMemPtr_V_WDATA;
output  [C_M_AXI_EXTMEMPTR_V_WSTRB_WIDTH - 1:0] m_axi_extMemPtr_V_WSTRB;
output   m_axi_extMemPtr_V_WLAST;
output  [C_M_AXI_EXTMEMPTR_V_ID_WIDTH - 1:0] m_axi_extMemPtr_V_WID;
output  [C_M_AXI_EXTMEMPTR_V_WUSER_WIDTH - 1:0] m_axi_extMemPtr_V_WUSER;
output   m_axi_extMemPtr_V_ARVALID;
input   m_axi_extMemPtr_V_ARREADY;
output  [C_M_AXI_EXTMEMPTR_V_ADDR_WIDTH - 1:0] m_axi_extMemPtr_V_ARADDR;
output  [C_M_AXI_EXTMEMPTR_V_ID_WIDTH - 1:0] m_axi_extMemPtr_V_ARID;
output  [7:0] m_axi_extMemPtr_V_ARLEN;
output  [2:0] m_axi_extMemPtr_V_ARSIZE;
output  [1:0] m_axi_extMemPtr_V_ARBURST;
output  [1:0] m_axi_extMemPtr_V_ARLOCK;
output  [3:0] m_axi_extMemPtr_V_ARCACHE;
output  [2:0] m_axi_extMemPtr_V_ARPROT;
output  [3:0] m_axi_extMemPtr_V_ARQOS;
output  [3:0] m_axi_extMemPtr_V_ARREGION;
output  [C_M_AXI_EXTMEMPTR_V_ARUSER_WIDTH - 1:0] m_axi_extMemPtr_V_ARUSER;
input   m_axi_extMemPtr_V_RVALID;
output   m_axi_extMemPtr_V_RREADY;
input  [C_M_AXI_EXTMEMPTR_V_DATA_WIDTH - 1:0] m_axi_extMemPtr_V_RDATA;
input   m_axi_extMemPtr_V_RLAST;
input  [C_M_AXI_EXTMEMPTR_V_ID_WIDTH - 1:0] m_axi_extMemPtr_V_RID;
input  [C_M_AXI_EXTMEMPTR_V_RUSER_WIDTH - 1:0] m_axi_extMemPtr_V_RUSER;
input  [1:0] m_axi_extMemPtr_V_RRESP;
input   m_axi_extMemPtr_V_BVALID;
output   m_axi_extMemPtr_V_BREADY;
input  [1:0] m_axi_extMemPtr_V_BRESP;
input  [C_M_AXI_EXTMEMPTR_V_ID_WIDTH - 1:0] m_axi_extMemPtr_V_BID;
input  [C_M_AXI_EXTMEMPTR_V_BUSER_WIDTH - 1:0] m_axi_extMemPtr_V_BUSER;
input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1:0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg    sample_in_0_data_reg;
reg    sample_in_0_vld_reg;
reg    sample_in_0_ack_out;
reg    sample_out_1_data_reg;
reg    sample_out_1_vld_reg;
reg    sample_out_1_vld_in;
reg    sample_out_1_ack_in;
wire   [31:0] baseMemAdr_V;
reg   [31:0] baseMemAdr_V_0_data_reg;
reg    baseMemAdr_V_0_vld_reg;
reg    baseMemAdr_V_0_ack_out;
reg   [31:0] sample_data0_1_data_reg;
reg    sample_data0_1_vld_reg;
reg    sample_data0_1_vld_in;
reg    sample_data0_1_ack_in;
reg    extMemPtr_V_blk_n_AR;
wire    ap_CS_fsm_state3;
reg    extMemPtr_V_blk_n_R;
wire    ap_CS_fsm_state10;
wire    extMemPtr_V_AWREADY;
wire    extMemPtr_V_WREADY;
reg    extMemPtr_V_ARVALID;
wire    extMemPtr_V_ARREADY;
wire   [31:0] extMemPtr_V_ARADDR;
wire    extMemPtr_V_RVALID;
reg    extMemPtr_V_RREADY;
wire   [31:0] extMemPtr_V_RDATA;
wire    extMemPtr_V_RLAST;
wire   [0:0] extMemPtr_V_RID;
wire   [0:0] extMemPtr_V_RUSER;
wire   [1:0] extMemPtr_V_RRESP;
wire    extMemPtr_V_BVALID;
wire   [1:0] extMemPtr_V_BRESP;
wire   [0:0] extMemPtr_V_BID;
wire   [0:0] extMemPtr_V_BUSER;
wire    ap_CS_fsm_state2;
reg   [29:0] r_V_5_reg_142;
reg   [31:0] data_V_reg_153;
wire   [0:0] trunc_ln219_fu_114_p1;
wire   [31:0] r_V_2_fu_129_p3;
wire    ap_CS_fsm_state11;
wire   [63:0] zext_ln544_fu_104_p1;
wire   [0:0] r_V_2_fu_129_p0;
wire   [31:0] r_V_fu_119_p2;
wire   [31:0] r_V_1_fu_124_p2;
wire    ap_CS_fsm_state12;
reg    ap_block_state12;
reg   [11:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 sample_in_0_data_reg = 1'b0;
#0 sample_in_0_vld_reg = 1'b0;
#0 sample_out_1_data_reg = 1'b0;
#0 sample_out_1_vld_reg = 1'b0;
#0 baseMemAdr_V_0_data_reg = 32'd0;
#0 baseMemAdr_V_0_vld_reg = 1'b0;
#0 sample_data0_1_data_reg = 32'd0;
#0 sample_data0_1_vld_reg = 1'b0;
end

pynq_sample_func_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
pynq_sample_func_AXILiteS_s_axi_U(
    .AWVALID(s_axi_AXILiteS_AWVALID),
    .AWREADY(s_axi_AXILiteS_AWREADY),
    .AWADDR(s_axi_AXILiteS_AWADDR),
    .WVALID(s_axi_AXILiteS_WVALID),
    .WREADY(s_axi_AXILiteS_WREADY),
    .WDATA(s_axi_AXILiteS_WDATA),
    .WSTRB(s_axi_AXILiteS_WSTRB),
    .ARVALID(s_axi_AXILiteS_ARVALID),
    .ARREADY(s_axi_AXILiteS_ARREADY),
    .ARADDR(s_axi_AXILiteS_ARADDR),
    .RVALID(s_axi_AXILiteS_RVALID),
    .RREADY(s_axi_AXILiteS_RREADY),
    .RDATA(s_axi_AXILiteS_RDATA),
    .RRESP(s_axi_AXILiteS_RRESP),
    .BVALID(s_axi_AXILiteS_BVALID),
    .BREADY(s_axi_AXILiteS_BREADY),
    .BRESP(s_axi_AXILiteS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .baseMemAdr_V(baseMemAdr_V),
    .sample_data0(sample_data0_1_data_reg),
    .sample_data0_ap_vld(sample_data0_1_vld_reg)
);

pynq_sample_func_extMemPtr_V_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_EXTMEMPTR_V_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_EXTMEMPTR_V_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_EXTMEMPTR_V_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_EXTMEMPTR_V_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_EXTMEMPTR_V_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_EXTMEMPTR_V_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_EXTMEMPTR_V_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_EXTMEMPTR_V_BUSER_WIDTH ),
    .C_TARGET_ADDR( C_M_AXI_EXTMEMPTR_V_TARGET_ADDR ),
    .C_USER_VALUE( C_M_AXI_EXTMEMPTR_V_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_EXTMEMPTR_V_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_EXTMEMPTR_V_CACHE_VALUE ))
pynq_sample_func_extMemPtr_V_m_axi_U(
    .AWVALID(m_axi_extMemPtr_V_AWVALID),
    .AWREADY(m_axi_extMemPtr_V_AWREADY),
    .AWADDR(m_axi_extMemPtr_V_AWADDR),
    .AWID(m_axi_extMemPtr_V_AWID),
    .AWLEN(m_axi_extMemPtr_V_AWLEN),
    .AWSIZE(m_axi_extMemPtr_V_AWSIZE),
    .AWBURST(m_axi_extMemPtr_V_AWBURST),
    .AWLOCK(m_axi_extMemPtr_V_AWLOCK),
    .AWCACHE(m_axi_extMemPtr_V_AWCACHE),
    .AWPROT(m_axi_extMemPtr_V_AWPROT),
    .AWQOS(m_axi_extMemPtr_V_AWQOS),
    .AWREGION(m_axi_extMemPtr_V_AWREGION),
    .AWUSER(m_axi_extMemPtr_V_AWUSER),
    .WVALID(m_axi_extMemPtr_V_WVALID),
    .WREADY(m_axi_extMemPtr_V_WREADY),
    .WDATA(m_axi_extMemPtr_V_WDATA),
    .WSTRB(m_axi_extMemPtr_V_WSTRB),
    .WLAST(m_axi_extMemPtr_V_WLAST),
    .WID(m_axi_extMemPtr_V_WID),
    .WUSER(m_axi_extMemPtr_V_WUSER),
    .ARVALID(m_axi_extMemPtr_V_ARVALID),
    .ARREADY(m_axi_extMemPtr_V_ARREADY),
    .ARADDR(m_axi_extMemPtr_V_ARADDR),
    .ARID(m_axi_extMemPtr_V_ARID),
    .ARLEN(m_axi_extMemPtr_V_ARLEN),
    .ARSIZE(m_axi_extMemPtr_V_ARSIZE),
    .ARBURST(m_axi_extMemPtr_V_ARBURST),
    .ARLOCK(m_axi_extMemPtr_V_ARLOCK),
    .ARCACHE(m_axi_extMemPtr_V_ARCACHE),
    .ARPROT(m_axi_extMemPtr_V_ARPROT),
    .ARQOS(m_axi_extMemPtr_V_ARQOS),
    .ARREGION(m_axi_extMemPtr_V_ARREGION),
    .ARUSER(m_axi_extMemPtr_V_ARUSER),
    .RVALID(m_axi_extMemPtr_V_RVALID),
    .RREADY(m_axi_extMemPtr_V_RREADY),
    .RDATA(m_axi_extMemPtr_V_RDATA),
    .RLAST(m_axi_extMemPtr_V_RLAST),
    .RID(m_axi_extMemPtr_V_RID),
    .RUSER(m_axi_extMemPtr_V_RUSER),
    .RRESP(m_axi_extMemPtr_V_RRESP),
    .BVALID(m_axi_extMemPtr_V_BVALID),
    .BREADY(m_axi_extMemPtr_V_BREADY),
    .BRESP(m_axi_extMemPtr_V_BRESP),
    .BID(m_axi_extMemPtr_V_BID),
    .BUSER(m_axi_extMemPtr_V_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(extMemPtr_V_ARVALID),
    .I_ARREADY(extMemPtr_V_ARREADY),
    .I_ARADDR(extMemPtr_V_ARADDR),
    .I_ARID(1'd0),
    .I_ARLEN(32'd1),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(extMemPtr_V_RVALID),
    .I_RREADY(extMemPtr_V_RREADY),
    .I_RDATA(extMemPtr_V_RDATA),
    .I_RID(extMemPtr_V_RID),
    .I_RUSER(extMemPtr_V_RUSER),
    .I_RRESP(extMemPtr_V_RRESP),
    .I_RLAST(extMemPtr_V_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(extMemPtr_V_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(extMemPtr_V_WREADY),
    .I_WDATA(32'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd0),
    .I_BVALID(extMemPtr_V_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(extMemPtr_V_BRESP),
    .I_BID(extMemPtr_V_BID),
    .I_BUSER(extMemPtr_V_BUSER)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (sample_data0_1_vld_reg == 1'b0) & (sample_data0_1_vld_in == 1'b1))) begin
        sample_data0_1_vld_reg <= 1'b1;
    end else if (((sample_data0_1_vld_in == 1'b0) & (1'b1 == 1'b1) & (sample_data0_1_vld_reg == 1'b1))) begin
        sample_data0_1_vld_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (baseMemAdr_V_0_vld_reg == 1'b0) & (1'b1 == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (baseMemAdr_V_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (baseMemAdr_V_0_vld_reg == 1'b1)))) begin
        baseMemAdr_V_0_data_reg <= baseMemAdr_V;
    end
end

always @ (posedge ap_clk) begin
    if (((extMemPtr_V_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        data_V_reg_153 <= extMemPtr_V_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        r_V_5_reg_142 <= {{baseMemAdr_V_0_data_reg[31:2]}};
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (sample_data0_1_vld_reg == 1'b0) & (sample_data0_1_vld_in == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (sample_data0_1_vld_in == 1'b1) & (sample_data0_1_vld_reg == 1'b1)))) begin
        sample_data0_1_data_reg <= r_V_2_fu_129_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (sample_in_0_vld_reg == 1'b0) & (1'b1 == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (sample_in_0_ack_out == 1'b1) & (1'b1 == 1'b1) & (sample_in_0_vld_reg == 1'b1)))) begin
        sample_in_0_data_reg <= sample_in;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (sample_out_1_vld_reg == 1'b0) & (sample_out_1_vld_in == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (sample_out_1_vld_in == 1'b1) & (sample_out_1_vld_reg == 1'b1)))) begin
        sample_out_1_data_reg <= trunc_ln219_fu_114_p1;
    end
end

always @ (*) begin
    if ((~((sample_out_1_ack_in == 1'b0) | (sample_data0_1_ack_in == 1'b0)) & (1'b1 == ap_CS_fsm_state12))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((sample_out_1_ack_in == 1'b0) | (sample_data0_1_ack_in == 1'b0)) & (1'b1 == ap_CS_fsm_state12))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (~((sample_out_1_ack_in == 1'b0) | (sample_data0_1_ack_in == 1'b0)) & (1'b1 == ap_CS_fsm_state12)))) begin
        baseMemAdr_V_0_ack_out = 1'b1;
    end else begin
        baseMemAdr_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((extMemPtr_V_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        extMemPtr_V_ARVALID = 1'b1;
    end else begin
        extMemPtr_V_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((extMemPtr_V_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        extMemPtr_V_RREADY = 1'b1;
    end else begin
        extMemPtr_V_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        extMemPtr_V_blk_n_AR = m_axi_extMemPtr_V_ARREADY;
    end else begin
        extMemPtr_V_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        extMemPtr_V_blk_n_R = m_axi_extMemPtr_V_RVALID;
    end else begin
        extMemPtr_V_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((sample_data0_1_vld_reg == 1'b0) | ((1'b1 == 1'b1) & (sample_data0_1_vld_reg == 1'b1)))) begin
        sample_data0_1_ack_in = 1'b1;
    end else begin
        sample_data0_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        sample_data0_1_vld_in = 1'b1;
    end else begin
        sample_data0_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (~((sample_out_1_ack_in == 1'b0) | (sample_data0_1_ack_in == 1'b0)) & (1'b1 == ap_CS_fsm_state12)))) begin
        sample_in_0_ack_out = 1'b1;
    end else begin
        sample_in_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if (((sample_out_1_vld_reg == 1'b0) | ((1'b1 == 1'b1) & (sample_out_1_vld_reg == 1'b1)))) begin
        sample_out_1_ack_in = 1'b1;
    end else begin
        sample_out_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if (((extMemPtr_V_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        sample_out_1_vld_in = 1'b1;
    end else begin
        sample_out_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((extMemPtr_V_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((extMemPtr_V_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if ((~((sample_out_1_ack_in == 1'b0) | (sample_data0_1_ack_in == 1'b0)) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state12 = ((sample_out_1_ack_in == 1'b0) | (sample_data0_1_ack_in == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign extMemPtr_V_ARADDR = zext_ln544_fu_104_p1;

assign r_V_1_fu_124_p2 = (data_V_reg_153 ^ 32'd4294967295);

assign r_V_2_fu_129_p0 = sample_in_0_data_reg;

assign r_V_2_fu_129_p3 = ((r_V_2_fu_129_p0[0:0] === 1'b1) ? r_V_fu_119_p2 : r_V_1_fu_124_p2);

assign r_V_fu_119_p2 = data_V_reg_153 << 32'd4;

assign sample_out = sample_out_1_data_reg;

assign trunc_ln219_fu_114_p1 = extMemPtr_V_RDATA[0:0];

assign zext_ln544_fu_104_p1 = r_V_5_reg_142;

endmodule //pynq_sample_func
