webtalk_init -webtalk_dir C:/Vivado_Project/Pynq-Examples/mnist/vivado/vivado.sim/sim_3/behav/xsim/xsim.dir/tb_nn_axis_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Sep 28 17:23:23 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1b5ed94d-9435-4879-99d6-e57c65a26199" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5c1c70e0323d40b4a37691a5198a315d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "70" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2712 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "11" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "687 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "71 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "2109" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "182" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "14.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "187356_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1339817971 -regid "" -xml C:/Vivado_Project/Pynq-Examples/mnist/vivado/vivado.sim/sim_3/behav/xsim/xsim.dir/tb_nn_axis_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Vivado_Project/Pynq-Examples/mnist/vivado/vivado.sim/sim_3/behav/xsim/xsim.dir/tb_nn_axis_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Vivado_Project/Pynq-Examples/mnist/vivado/vivado.sim/sim_3/behav/xsim/xsim.dir/tb_nn_axis_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
