-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity copy_mem is
generic (
    C_M_AXI_EXTMEMPTR_V_ADDR_WIDTH : INTEGER := 32;
    C_M_AXI_EXTMEMPTR_V_ID_WIDTH : INTEGER := 1;
    C_M_AXI_EXTMEMPTR_V_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_EXTMEMPTR_V_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_EXTMEMPTR_V_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_EXTMEMPTR_V_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_EXTMEMPTR_V_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_EXTMEMPTR_V_BUSER_WIDTH : INTEGER := 1;
    C_S_AXI_AXILITES_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_AXILITES_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_EXTMEMPTR_V_TARGET_ADDR : INTEGER := 0;
    C_M_AXI_EXTMEMPTR_V_USER_VALUE : INTEGER := 0;
    C_M_AXI_EXTMEMPTR_V_PROT_VALUE : INTEGER := 0;
    C_M_AXI_EXTMEMPTR_V_CACHE_VALUE : INTEGER := 3 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    m_axi_extMemPtr_V_AWVALID : OUT STD_LOGIC;
    m_axi_extMemPtr_V_AWREADY : IN STD_LOGIC;
    m_axi_extMemPtr_V_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_EXTMEMPTR_V_ADDR_WIDTH-1 downto 0);
    m_axi_extMemPtr_V_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_EXTMEMPTR_V_ID_WIDTH-1 downto 0);
    m_axi_extMemPtr_V_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_extMemPtr_V_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_extMemPtr_V_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_extMemPtr_V_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_extMemPtr_V_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_extMemPtr_V_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_extMemPtr_V_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_extMemPtr_V_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_extMemPtr_V_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_EXTMEMPTR_V_AWUSER_WIDTH-1 downto 0);
    m_axi_extMemPtr_V_WVALID : OUT STD_LOGIC;
    m_axi_extMemPtr_V_WREADY : IN STD_LOGIC;
    m_axi_extMemPtr_V_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_EXTMEMPTR_V_DATA_WIDTH-1 downto 0);
    m_axi_extMemPtr_V_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_EXTMEMPTR_V_DATA_WIDTH/8-1 downto 0);
    m_axi_extMemPtr_V_WLAST : OUT STD_LOGIC;
    m_axi_extMemPtr_V_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_EXTMEMPTR_V_ID_WIDTH-1 downto 0);
    m_axi_extMemPtr_V_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_EXTMEMPTR_V_WUSER_WIDTH-1 downto 0);
    m_axi_extMemPtr_V_ARVALID : OUT STD_LOGIC;
    m_axi_extMemPtr_V_ARREADY : IN STD_LOGIC;
    m_axi_extMemPtr_V_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_EXTMEMPTR_V_ADDR_WIDTH-1 downto 0);
    m_axi_extMemPtr_V_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_EXTMEMPTR_V_ID_WIDTH-1 downto 0);
    m_axi_extMemPtr_V_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_extMemPtr_V_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_extMemPtr_V_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_extMemPtr_V_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_extMemPtr_V_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_extMemPtr_V_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_extMemPtr_V_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_extMemPtr_V_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_extMemPtr_V_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_EXTMEMPTR_V_ARUSER_WIDTH-1 downto 0);
    m_axi_extMemPtr_V_RVALID : IN STD_LOGIC;
    m_axi_extMemPtr_V_RREADY : OUT STD_LOGIC;
    m_axi_extMemPtr_V_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_EXTMEMPTR_V_DATA_WIDTH-1 downto 0);
    m_axi_extMemPtr_V_RLAST : IN STD_LOGIC;
    m_axi_extMemPtr_V_RID : IN STD_LOGIC_VECTOR (C_M_AXI_EXTMEMPTR_V_ID_WIDTH-1 downto 0);
    m_axi_extMemPtr_V_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_EXTMEMPTR_V_RUSER_WIDTH-1 downto 0);
    m_axi_extMemPtr_V_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_extMemPtr_V_BVALID : IN STD_LOGIC;
    m_axi_extMemPtr_V_BREADY : OUT STD_LOGIC;
    m_axi_extMemPtr_V_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_extMemPtr_V_BID : IN STD_LOGIC_VECTOR (C_M_AXI_EXTMEMPTR_V_ID_WIDTH-1 downto 0);
    m_axi_extMemPtr_V_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_EXTMEMPTR_V_BUSER_WIDTH-1 downto 0);
    s_axi_AXILiteS_AWVALID : IN STD_LOGIC;
    s_axi_AXILiteS_AWREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_ADDR_WIDTH-1 downto 0);
    s_axi_AXILiteS_WVALID : IN STD_LOGIC;
    s_axi_AXILiteS_WREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH-1 downto 0);
    s_axi_AXILiteS_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH/8-1 downto 0);
    s_axi_AXILiteS_ARVALID : IN STD_LOGIC;
    s_axi_AXILiteS_ARREADY : OUT STD_LOGIC;
    s_axi_AXILiteS_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_AXILITES_ADDR_WIDTH-1 downto 0);
    s_axi_AXILiteS_RVALID : OUT STD_LOGIC;
    s_axi_AXILiteS_RREADY : IN STD_LOGIC;
    s_axi_AXILiteS_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_AXILITES_DATA_WIDTH-1 downto 0);
    s_axi_AXILiteS_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_AXILiteS_BVALID : OUT STD_LOGIC;
    s_axi_AXILiteS_BREADY : IN STD_LOGIC;
    s_axi_AXILiteS_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of copy_mem is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "copy_mem,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=17.500000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=1027,HLS_SYN_LUT=1092,HLS_VERSION=2020_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (16 downto 0) := "00000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (16 downto 0) := "00000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (16 downto 0) := "00000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (16 downto 0) := "00000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (16 downto 0) := "00000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (16 downto 0) := "00000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (16 downto 0) := "00001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (16 downto 0) := "00010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (16 downto 0) := "00100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (16 downto 0) := "01000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (16 downto 0) := "10000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_M_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal inputBaseMemAdr_V : STD_LOGIC_VECTOR (31 downto 0);
    signal inputBaseMemAdr_V_0_data_reg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal inputBaseMemAdr_V_0_vld_reg : STD_LOGIC := '0';
    signal inputBaseMemAdr_V_0_ack_out : STD_LOGIC;
    signal outputBaseMemAdr_V : STD_LOGIC_VECTOR (31 downto 0);
    signal outputBaseMemAdr_V_0_data_reg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal outputBaseMemAdr_V_0_vld_reg : STD_LOGIC := '0';
    signal outputBaseMemAdr_V_0_ack_out : STD_LOGIC;
    signal loadSize_V : STD_LOGIC_VECTOR (31 downto 0);
    signal loadSize_V_0_data_reg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal loadSize_V_0_vld_reg : STD_LOGIC := '0';
    signal loadSize_V_0_ack_out : STD_LOGIC;
    signal extMemPtr_V_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal extMemPtr_V_blk_n_R : STD_LOGIC;
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal extMemPtr_V_blk_n_AW : STD_LOGIC;
    signal extMemPtr_V_blk_n_W : STD_LOGIC;
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal extMemPtr_V_blk_n_B : STD_LOGIC;
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal extMemPtr_V_AWVALID : STD_LOGIC;
    signal extMemPtr_V_AWREADY : STD_LOGIC;
    signal extMemPtr_V_WVALID : STD_LOGIC;
    signal extMemPtr_V_WREADY : STD_LOGIC;
    signal extMemPtr_V_ARVALID : STD_LOGIC;
    signal extMemPtr_V_ARREADY : STD_LOGIC;
    signal extMemPtr_V_RVALID : STD_LOGIC;
    signal extMemPtr_V_RREADY : STD_LOGIC;
    signal extMemPtr_V_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal extMemPtr_V_RLAST : STD_LOGIC;
    signal extMemPtr_V_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal extMemPtr_V_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal extMemPtr_V_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal extMemPtr_V_BVALID : STD_LOGIC;
    signal extMemPtr_V_BREADY : STD_LOGIC;
    signal extMemPtr_V_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal extMemPtr_V_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal extMemPtr_V_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal loadSize_V_read_reg_180 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal zext_ln215_fu_127_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln215_reg_185 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln20_fu_131_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal zext_ln20_reg_190 : STD_LOGIC_VECTOR (32 downto 0);
    signal i_fu_140_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_reg_198 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal extMemPtr_V_addr_reg_203 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln20_fu_135_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal extMemPtr_V_addr_1_reg_209 : STD_LOGIC_VECTOR (31 downto 0);
    signal data_V_reg_215 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_op_assign_reg_96 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln544_fu_155_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln544_1_fu_170_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal r_V_fu_107_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal r_V_1_fu_117_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal sext_ln215_fu_146_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_fu_150_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal ret_V_1_fu_165_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (16 downto 0);

    component copy_mem_AXILiteS_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        inputBaseMemAdr_V : OUT STD_LOGIC_VECTOR (31 downto 0);
        outputBaseMemAdr_V : OUT STD_LOGIC_VECTOR (31 downto 0);
        loadSize_V : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component copy_mem_extMemPtr_V_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_DW : INTEGER;
        USER_AW : INTEGER;
        USER_MAXREQS : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_TARGET_ADDR : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_ARVALID : IN STD_LOGIC;
        I_ARREADY : OUT STD_LOGIC;
        I_ARADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_RVALID : OUT STD_LOGIC;
        I_RREADY : IN STD_LOGIC;
        I_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_RID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_RLAST : OUT STD_LOGIC;
        I_AWVALID : IN STD_LOGIC;
        I_AWREADY : OUT STD_LOGIC;
        I_AWADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_WVALID : IN STD_LOGIC;
        I_WREADY : OUT STD_LOGIC;
        I_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_WID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WLAST : IN STD_LOGIC;
        I_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_BVALID : OUT STD_LOGIC;
        I_BREADY : IN STD_LOGIC;
        I_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_BID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_BUSER : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    copy_mem_AXILiteS_s_axi_U : component copy_mem_AXILiteS_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_AXILITES_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_AXILITES_DATA_WIDTH)
    port map (
        AWVALID => s_axi_AXILiteS_AWVALID,
        AWREADY => s_axi_AXILiteS_AWREADY,
        AWADDR => s_axi_AXILiteS_AWADDR,
        WVALID => s_axi_AXILiteS_WVALID,
        WREADY => s_axi_AXILiteS_WREADY,
        WDATA => s_axi_AXILiteS_WDATA,
        WSTRB => s_axi_AXILiteS_WSTRB,
        ARVALID => s_axi_AXILiteS_ARVALID,
        ARREADY => s_axi_AXILiteS_ARREADY,
        ARADDR => s_axi_AXILiteS_ARADDR,
        RVALID => s_axi_AXILiteS_RVALID,
        RREADY => s_axi_AXILiteS_RREADY,
        RDATA => s_axi_AXILiteS_RDATA,
        RRESP => s_axi_AXILiteS_RRESP,
        BVALID => s_axi_AXILiteS_BVALID,
        BREADY => s_axi_AXILiteS_BREADY,
        BRESP => s_axi_AXILiteS_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        inputBaseMemAdr_V => inputBaseMemAdr_V,
        outputBaseMemAdr_V => outputBaseMemAdr_V,
        loadSize_V => loadSize_V);

    copy_mem_extMemPtr_V_m_axi_U : component copy_mem_extMemPtr_V_m_axi
    generic map (
        CONSERVATIVE => 0,
        USER_DW => 32,
        USER_AW => 32,
        USER_MAXREQS => 5,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_EXTMEMPTR_V_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_EXTMEMPTR_V_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_EXTMEMPTR_V_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_EXTMEMPTR_V_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_EXTMEMPTR_V_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_EXTMEMPTR_V_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_EXTMEMPTR_V_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_EXTMEMPTR_V_BUSER_WIDTH,
        C_TARGET_ADDR => C_M_AXI_EXTMEMPTR_V_TARGET_ADDR,
        C_USER_VALUE => C_M_AXI_EXTMEMPTR_V_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_EXTMEMPTR_V_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_EXTMEMPTR_V_CACHE_VALUE)
    port map (
        AWVALID => m_axi_extMemPtr_V_AWVALID,
        AWREADY => m_axi_extMemPtr_V_AWREADY,
        AWADDR => m_axi_extMemPtr_V_AWADDR,
        AWID => m_axi_extMemPtr_V_AWID,
        AWLEN => m_axi_extMemPtr_V_AWLEN,
        AWSIZE => m_axi_extMemPtr_V_AWSIZE,
        AWBURST => m_axi_extMemPtr_V_AWBURST,
        AWLOCK => m_axi_extMemPtr_V_AWLOCK,
        AWCACHE => m_axi_extMemPtr_V_AWCACHE,
        AWPROT => m_axi_extMemPtr_V_AWPROT,
        AWQOS => m_axi_extMemPtr_V_AWQOS,
        AWREGION => m_axi_extMemPtr_V_AWREGION,
        AWUSER => m_axi_extMemPtr_V_AWUSER,
        WVALID => m_axi_extMemPtr_V_WVALID,
        WREADY => m_axi_extMemPtr_V_WREADY,
        WDATA => m_axi_extMemPtr_V_WDATA,
        WSTRB => m_axi_extMemPtr_V_WSTRB,
        WLAST => m_axi_extMemPtr_V_WLAST,
        WID => m_axi_extMemPtr_V_WID,
        WUSER => m_axi_extMemPtr_V_WUSER,
        ARVALID => m_axi_extMemPtr_V_ARVALID,
        ARREADY => m_axi_extMemPtr_V_ARREADY,
        ARADDR => m_axi_extMemPtr_V_ARADDR,
        ARID => m_axi_extMemPtr_V_ARID,
        ARLEN => m_axi_extMemPtr_V_ARLEN,
        ARSIZE => m_axi_extMemPtr_V_ARSIZE,
        ARBURST => m_axi_extMemPtr_V_ARBURST,
        ARLOCK => m_axi_extMemPtr_V_ARLOCK,
        ARCACHE => m_axi_extMemPtr_V_ARCACHE,
        ARPROT => m_axi_extMemPtr_V_ARPROT,
        ARQOS => m_axi_extMemPtr_V_ARQOS,
        ARREGION => m_axi_extMemPtr_V_ARREGION,
        ARUSER => m_axi_extMemPtr_V_ARUSER,
        RVALID => m_axi_extMemPtr_V_RVALID,
        RREADY => m_axi_extMemPtr_V_RREADY,
        RDATA => m_axi_extMemPtr_V_RDATA,
        RLAST => m_axi_extMemPtr_V_RLAST,
        RID => m_axi_extMemPtr_V_RID,
        RUSER => m_axi_extMemPtr_V_RUSER,
        RRESP => m_axi_extMemPtr_V_RRESP,
        BVALID => m_axi_extMemPtr_V_BVALID,
        BREADY => m_axi_extMemPtr_V_BREADY,
        BRESP => m_axi_extMemPtr_V_BRESP,
        BID => m_axi_extMemPtr_V_BID,
        BUSER => m_axi_extMemPtr_V_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_ARVALID => extMemPtr_V_ARVALID,
        I_ARREADY => extMemPtr_V_ARREADY,
        I_ARADDR => extMemPtr_V_addr_reg_203,
        I_ARID => ap_const_lv1_0,
        I_ARLEN => ap_const_lv32_1,
        I_ARSIZE => ap_const_lv3_0,
        I_ARLOCK => ap_const_lv2_0,
        I_ARCACHE => ap_const_lv4_0,
        I_ARQOS => ap_const_lv4_0,
        I_ARPROT => ap_const_lv3_0,
        I_ARUSER => ap_const_lv1_0,
        I_ARBURST => ap_const_lv2_0,
        I_ARREGION => ap_const_lv4_0,
        I_RVALID => extMemPtr_V_RVALID,
        I_RREADY => extMemPtr_V_RREADY,
        I_RDATA => extMemPtr_V_RDATA,
        I_RID => extMemPtr_V_RID,
        I_RUSER => extMemPtr_V_RUSER,
        I_RRESP => extMemPtr_V_RRESP,
        I_RLAST => extMemPtr_V_RLAST,
        I_AWVALID => extMemPtr_V_AWVALID,
        I_AWREADY => extMemPtr_V_AWREADY,
        I_AWADDR => extMemPtr_V_addr_1_reg_209,
        I_AWID => ap_const_lv1_0,
        I_AWLEN => ap_const_lv32_1,
        I_AWSIZE => ap_const_lv3_0,
        I_AWLOCK => ap_const_lv2_0,
        I_AWCACHE => ap_const_lv4_0,
        I_AWQOS => ap_const_lv4_0,
        I_AWPROT => ap_const_lv3_0,
        I_AWUSER => ap_const_lv1_0,
        I_AWBURST => ap_const_lv2_0,
        I_AWREGION => ap_const_lv4_0,
        I_WVALID => extMemPtr_V_WVALID,
        I_WREADY => extMemPtr_V_WREADY,
        I_WDATA => data_V_reg_215,
        I_WID => ap_const_lv1_0,
        I_WUSER => ap_const_lv1_0,
        I_WLAST => ap_const_logic_0,
        I_WSTRB => ap_const_lv4_F,
        I_BVALID => extMemPtr_V_BVALID,
        I_BREADY => extMemPtr_V_BREADY,
        I_BRESP => extMemPtr_V_BRESP,
        I_BID => extMemPtr_V_BID,
        I_BUSER => extMemPtr_V_BUSER);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_op_assign_reg_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((extMemPtr_V_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
                i_op_assign_reg_96 <= i_reg_198;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                i_op_assign_reg_96 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    inputBaseMemAdr_V_0_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    loadSize_V_0_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;

    outputBaseMemAdr_V_0_vld_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((extMemPtr_V_RVALID = ap_const_logic_0) or (extMemPtr_V_AWREADY = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                data_V_reg_215 <= extMemPtr_V_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln20_fu_135_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                extMemPtr_V_addr_1_reg_209 <= sext_ln544_1_fu_170_p1(32 - 1 downto 0);
                extMemPtr_V_addr_reg_203 <= sext_ln544_fu_155_p1(32 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                i_reg_198 <= i_fu_140_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (inputBaseMemAdr_V_0_vld_reg = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_1)) or (not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (inputBaseMemAdr_V_0_ack_out = ap_const_logic_1) and (ap_const_logic_1 = ap_const_logic_1) and (inputBaseMemAdr_V_0_vld_reg = ap_const_logic_1)))) then
                inputBaseMemAdr_V_0_data_reg <= inputBaseMemAdr_V;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (loadSize_V_0_vld_reg = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_1)) or (not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (loadSize_V_0_ack_out = ap_const_logic_1) and (ap_const_logic_1 = ap_const_logic_1) and (loadSize_V_0_vld_reg = ap_const_logic_1)))) then
                loadSize_V_0_data_reg <= loadSize_V;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                loadSize_V_read_reg_180 <= loadSize_V_0_data_reg;
                    zext_ln20_reg_190(29 downto 0) <= zext_ln20_fu_131_p1(29 downto 0);
                    zext_ln215_reg_185(29 downto 0) <= zext_ln215_fu_127_p1(29 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (outputBaseMemAdr_V_0_vld_reg = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_1)) or (not(((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) and (outputBaseMemAdr_V_0_ack_out = ap_const_logic_1) and (ap_const_logic_1 = ap_const_logic_1) and (outputBaseMemAdr_V_0_vld_reg = ap_const_logic_1)))) then
                outputBaseMemAdr_V_0_data_reg <= outputBaseMemAdr_V;
            end if;
        end if;
    end process;
    zext_ln215_reg_185(32 downto 30) <= "000";
    zext_ln20_reg_190(32 downto 30) <= "000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, ap_CS_fsm_state11, ap_CS_fsm_state12, ap_CS_fsm_state17, extMemPtr_V_AWREADY, extMemPtr_V_WREADY, extMemPtr_V_ARREADY, extMemPtr_V_RVALID, extMemPtr_V_BVALID, ap_CS_fsm_state3, icmp_ln20_fu_135_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln20_fu_135_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((extMemPtr_V_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                if ((not(((extMemPtr_V_RVALID = ap_const_logic_0) or (extMemPtr_V_AWREADY = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                if (((extMemPtr_V_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                if (((extMemPtr_V_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state17;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_done_assign_proc : process(ap_CS_fsm_state3, icmp_ln20_fu_135_p2)
    begin
        if (((icmp_ln20_fu_135_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, icmp_ln20_fu_135_p2)
    begin
        if (((icmp_ln20_fu_135_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    extMemPtr_V_ARVALID_assign_proc : process(ap_CS_fsm_state4, extMemPtr_V_ARREADY)
    begin
        if (((extMemPtr_V_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            extMemPtr_V_ARVALID <= ap_const_logic_1;
        else 
            extMemPtr_V_ARVALID <= ap_const_logic_0;
        end if; 
    end process;


    extMemPtr_V_AWVALID_assign_proc : process(ap_CS_fsm_state11, extMemPtr_V_AWREADY, extMemPtr_V_RVALID)
    begin
        if ((not(((extMemPtr_V_RVALID = ap_const_logic_0) or (extMemPtr_V_AWREADY = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            extMemPtr_V_AWVALID <= ap_const_logic_1;
        else 
            extMemPtr_V_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    extMemPtr_V_BREADY_assign_proc : process(ap_CS_fsm_state17, extMemPtr_V_BVALID)
    begin
        if (((extMemPtr_V_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            extMemPtr_V_BREADY <= ap_const_logic_1;
        else 
            extMemPtr_V_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    extMemPtr_V_RREADY_assign_proc : process(ap_CS_fsm_state11, extMemPtr_V_AWREADY, extMemPtr_V_RVALID)
    begin
        if ((not(((extMemPtr_V_RVALID = ap_const_logic_0) or (extMemPtr_V_AWREADY = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            extMemPtr_V_RREADY <= ap_const_logic_1;
        else 
            extMemPtr_V_RREADY <= ap_const_logic_0;
        end if; 
    end process;


    extMemPtr_V_WVALID_assign_proc : process(ap_CS_fsm_state12, extMemPtr_V_WREADY)
    begin
        if (((extMemPtr_V_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            extMemPtr_V_WVALID <= ap_const_logic_1;
        else 
            extMemPtr_V_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    extMemPtr_V_blk_n_AR_assign_proc : process(m_axi_extMemPtr_V_ARREADY, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            extMemPtr_V_blk_n_AR <= m_axi_extMemPtr_V_ARREADY;
        else 
            extMemPtr_V_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    extMemPtr_V_blk_n_AW_assign_proc : process(m_axi_extMemPtr_V_AWREADY, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            extMemPtr_V_blk_n_AW <= m_axi_extMemPtr_V_AWREADY;
        else 
            extMemPtr_V_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    extMemPtr_V_blk_n_B_assign_proc : process(m_axi_extMemPtr_V_BVALID, ap_CS_fsm_state17)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            extMemPtr_V_blk_n_B <= m_axi_extMemPtr_V_BVALID;
        else 
            extMemPtr_V_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    extMemPtr_V_blk_n_R_assign_proc : process(m_axi_extMemPtr_V_RVALID, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            extMemPtr_V_blk_n_R <= m_axi_extMemPtr_V_RVALID;
        else 
            extMemPtr_V_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    extMemPtr_V_blk_n_W_assign_proc : process(m_axi_extMemPtr_V_WREADY, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            extMemPtr_V_blk_n_W <= m_axi_extMemPtr_V_WREADY;
        else 
            extMemPtr_V_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    i_fu_140_p2 <= std_logic_vector(signed(i_op_assign_reg_96) + signed(ap_const_lv32_1));
    icmp_ln20_fu_135_p2 <= "1" when (i_op_assign_reg_96 = loadSize_V_read_reg_180) else "0";

    inputBaseMemAdr_V_0_ack_out_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, icmp_ln20_fu_135_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((icmp_ln20_fu_135_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            inputBaseMemAdr_V_0_ack_out <= ap_const_logic_1;
        else 
            inputBaseMemAdr_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    loadSize_V_0_ack_out_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, icmp_ln20_fu_135_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((icmp_ln20_fu_135_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            loadSize_V_0_ack_out <= ap_const_logic_1;
        else 
            loadSize_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    outputBaseMemAdr_V_0_ack_out_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, icmp_ln20_fu_135_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((icmp_ln20_fu_135_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            outputBaseMemAdr_V_0_ack_out <= ap_const_logic_1;
        else 
            outputBaseMemAdr_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;

    r_V_1_fu_117_p4 <= outputBaseMemAdr_V_0_data_reg(31 downto 2);
    r_V_fu_107_p4 <= inputBaseMemAdr_V_0_data_reg(31 downto 2);
    ret_V_1_fu_165_p2 <= std_logic_vector(signed(sext_ln215_fu_146_p1) + signed(zext_ln20_reg_190));
    ret_V_fu_150_p2 <= std_logic_vector(signed(sext_ln215_fu_146_p1) + signed(zext_ln215_reg_185));
        sext_ln215_fu_146_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(i_op_assign_reg_96),33));

        sext_ln544_1_fu_170_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ret_V_1_fu_165_p2),64));

        sext_ln544_fu_155_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(ret_V_fu_150_p2),64));

    zext_ln20_fu_131_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_V_1_fu_117_p4),33));
    zext_ln215_fu_127_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_V_fu_107_p4),33));
end behav;
