#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : base.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Oct 07 15:01:11 +0900 2020
# SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: base.sh [-help]
# usage: base.sh [-lib_map_path]
# usage: base.sh [-noclean_files]
# usage: base.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'base.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm xil_defaultlib axi_lite_ipif_v3_0_4 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_gpio_v2_0_23 xlconcat_v2_1_3 xlconstant_v1_1_7 lib_pkg_v1_0_2 axi_iic_v2_0_24 axi_intc_v4_1_14 lmb_v10_v3_0_11 blk_mem_gen_v8_4_4 lmb_bram_if_cntlr_v4_0_18 microblaze_v11_0_3 axi_bram_ctrl_v4_1_3 proc_sys_reset_v5_0_13 dist_mem_gen_v8_0_13 lib_srl_fifo_v1_0_2 fifo_generator_v13_2_5 lib_fifo_v1_0_14 axi_quad_spi_v3_2_20 xlslice_v1_0_2 axi_timer_v2_0_23 axi_uartlite_v2_0_25 mdm_v3_2_18 axi_infrastructure_v1_1_0 axi_vip_v1_1_7 processing_system7_vip_v1_0_9 axi_datamover_v5_1_23 axi_sg_v4_1_13 axi_dma_v7_1_22 axis_infrastructure_v1_1_0 axis_data_fifo_v2_0_3 lib_bmg_v1_0_13 axi_vdma_v6_3_9 axis_register_slice_v1_1_21 v_vid_in_axi4s_v4_0_9 v_tc_v6_2_0 v_tc_v6_1_13 v_axi4s_vid_out_v4_0_10 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_21 axi_data_fifo_v2_1_20 axi_crossbar_v2_1_22 axi_protocol_converter_v2_1_21 axi_clock_converter_v2_1_20 axi_dwidth_converter_v2_1_21)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "base.sh - Script generated by export_simulation (Vivado v2020.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ipshared/f35b/src/family_support.vhd" \
    "$ref_dir/../../../bd/base/ipshared/f35b/src/common_types.vhd" \
    "$ref_dir/../../../bd/base/ipshared/f35b/src/pselect_f.vhd" \
    "$ref_dir/../../../bd/base/ipshared/f35b/src/address_decoder.vhd" \
    "$ref_dir/../../../bd/base/ipshared/f35b/src/slave_attachment.vhd" \
    "$ref_dir/../../../bd/base/ipshared/f35b/src/axi_lite_ipif.vhd" \
    "$ref_dir/../../../bd/base/ipshared/f35b/src/user_logic.vhd" \
    "$ref_dir/../../../bd/base/ipshared/f35b/src/iis_deser.vhd" \
    "$ref_dir/../../../bd/base/ipshared/f35b/src/iis_ser.vhd" \
    "$ref_dir/../../../bd/base/ipshared/f35b/src/i2s_ctrl.vhd" \
    "$ref_dir/../../../bd/base/ip/base_audio_codec_ctrl_0_0/sim/base_audio_codec_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_23 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/bb35/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_btns_gpio_0/sim/base_btns_gpio_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_clk_wiz_10MHz_0/base_clk_wiz_10MHz_0_clk_wiz.v" \
    "$ref_dir/../../../bd/base/ip/base_clk_wiz_10MHz_0/base_clk_wiz_10MHz_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/442e/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_concat_interrupts_0/sim/base_concat_interrupts_0.v" \
    "$ref_dir/../../../bd/base/ip/base_concat_pmodb_0/sim/base_concat_pmodb_0.v" \
    "$ref_dir/../../../bd/base/ip/base_concat_rp_0/sim/base_concat_rp_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_constant_8bit_0_0/sim/base_constant_8bit_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_arduino_gpio_0/sim/base_arduino_gpio_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ipshared/10e3/dff_en_reset_vector.v" \
    "$ref_dir/../../../bd/base/ip/base_dff_en_reset_vector_0_0/sim/base_dff_en_reset_vector_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_iic_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/d1e4/hdl/axi_iic_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_iic_direct_0/sim/base_iic_direct_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_14 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/f78a/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_intc_0/sim/base_intc_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_interrupt_concat_0/sim/base_interrupt_concat_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_intr_0/sim/base_intr_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ipshared/6c92/src/io_switch.v" \
    "$ref_dir/../../../bd/base/ipshared/6c92/src/io_switch_bit.v" \
    "$ref_dir/../../../bd/base/ipshared/6c92/hdl/io_switch_v1_1_S_AXI.v" \
    "$ref_dir/../../../bd/base/ipshared/6c92/hdl/io_switch_v1_1.v" \
    "$ref_dir/../../../bd/base/ip/base_io_switch_0/sim/base_io_switch_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lmb_v10_v3_0_11 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/c2ed/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_dlmb_v10_0/sim/base_dlmb_v10_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_ilmb_v10_0/sim/base_ilmb_v10_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_lmb_bram_0/sim/base_lmb_bram_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lmb_bram_if_cntlr_v4_0_18 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/246e/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_lmb_bram_if_cntlr_0/sim/base_lmb_bram_if_cntlr_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_logic_1_0/sim/base_logic_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work microblaze_v11_0_3 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/1efc/hdl/microblaze_v11_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_mb_0/sim/base_mb_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_bram_ctrl_v4_1_3 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/db86/hdl/axi_bram_ctrl_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_mb_bram_ctrl_0/sim/base_mb_bram_ctrl_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_rst_clk_wiz_1_100M_0/sim/base_rst_clk_wiz_1_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work dist_mem_gen_v8_0_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/0bf5/simulation/dist_mem_gen_v8_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_quad_spi_v3_2_20 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/1735/hdl/axi_quad_spi_v3_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_spi_direct_0/sim/base_spi_direct_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_spi_shared_0/sim/base_spi_shared_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_mb3_timer_capture_0_0/sim/base_mb3_timer_capture_0_0.v" \
    "$ref_dir/../../../bd/base/ip/base_mb3_timer_capture_1_0/sim/base_mb3_timer_capture_1_0.v" \
    "$ref_dir/../../../bd/base/ip/base_mb3_timer_capture_2_0/sim/base_mb3_timer_capture_2_0.v" \
    "$ref_dir/../../../bd/base/ip/base_mb3_timer_capture_3_0/sim/base_mb3_timer_capture_3_0.v" \
    "$ref_dir/../../../bd/base/ip/base_mb3_timer_capture_4_0/sim/base_mb3_timer_capture_4_0.v" \
    "$ref_dir/../../../bd/base/ip/base_mb3_timer_capture_5_0/sim/base_mb3_timer_capture_5_0.v" \
    "$ref_dir/../../../bd/base/ip/base_mb3_timer_capture_6_0/sim/base_mb3_timer_capture_6_0.v" \
    "$ref_dir/../../../bd/base/ip/base_mb3_timer_capture_7_0/sim/base_mb3_timer_capture_7_0.v" \
    "$ref_dir/../../../bd/base/ip/base_mb3_timer_generate_0/sim/base_mb3_timer_generate_0.v" \
    "$ref_dir/../../../bd/base/ip/base_mb3_timer_pwm_0/sim/base_mb3_timer_pwm_0.v" \
    "$ref_dir/../../../bd/base/ip/base_mb3_timers_interrupt_0/sim/base_mb3_timers_interrupt_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_timer_v2_0_23 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/eb71/hdl/axi_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_timer_0_0/sim/base_timer_0_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_timer_1_0/sim/base_timer_1_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_timer_2_0/sim/base_timer_2_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_timer_3_0/sim/base_timer_3_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_timer_4_0/sim/base_timer_4_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_timer_5_0/sim/base_timer_5_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uartlite_v2_0_25 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/43b7/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_uartlite_0/sim/base_uartlite_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_xadc_0/proc_common_v3_30_a/hdl/src/vhdl/base_xadc_0_conv_funs_pkg.vhd" \
    "$ref_dir/../../../bd/base/ip/base_xadc_0/proc_common_v3_30_a/hdl/src/vhdl/base_xadc_0_proc_common_pkg.vhd" \
    "$ref_dir/../../../bd/base/ip/base_xadc_0/proc_common_v3_30_a/hdl/src/vhdl/base_xadc_0_ipif_pkg.vhd" \
    "$ref_dir/../../../bd/base/ip/base_xadc_0/proc_common_v3_30_a/hdl/src/vhdl/base_xadc_0_family_support.vhd" \
    "$ref_dir/../../../bd/base/ip/base_xadc_0/proc_common_v3_30_a/hdl/src/vhdl/base_xadc_0_family.vhd" \
    "$ref_dir/../../../bd/base/ip/base_xadc_0/proc_common_v3_30_a/hdl/src/vhdl/base_xadc_0_soft_reset.vhd" \
    "$ref_dir/../../../bd/base/ip/base_xadc_0/proc_common_v3_30_a/hdl/src/vhdl/base_xadc_0_pselect_f.vhd" \
    "$ref_dir/../../../bd/base/ip/base_xadc_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/base_xadc_0_address_decoder.vhd" \
    "$ref_dir/../../../bd/base/ip/base_xadc_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/base_xadc_0_slave_attachment.vhd" \
    "$ref_dir/../../../bd/base/ip/base_xadc_0/interrupt_control_v2_01_a/hdl/src/vhdl/base_xadc_0_interrupt_control.vhd" \
    "$ref_dir/../../../bd/base/ip/base_xadc_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/base_xadc_0_axi_lite_ipif.vhd" \
    "$ref_dir/../../../bd/base/ip/base_xadc_0/base_xadc_0_xadc_core_drp.vhd" \
    "$ref_dir/../../../bd/base/ip/base_xadc_0/base_xadc_0_axi_xadc.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_xadc_0/base_xadc_0.v" \
    "$ref_dir/../../../bd/base/ip/base_iop_interrupts_0/sim/base_iop_interrupts_0.v" \
    "$ref_dir/../../../bd/base/ip/base_dff_en_reset_vector_0_1/sim/base_dff_en_reset_vector_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_gpio_0/sim/base_gpio_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_iic_0/sim/base_iic_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_intc_1/sim/base_intc_1.vhd" \
    "$ref_dir/../../../bd/base/ip/base_intr_1/sim/base_intr_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_intr_concat_0/sim/base_intr_concat_0.v" \
    "$ref_dir/../../../bd/base/ip/base_io_switch_1/sim/base_io_switch_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_dlmb_v10_1/sim/base_dlmb_v10_1.vhd" \
    "$ref_dir/../../../bd/base/ip/base_ilmb_v10_1/sim/base_ilmb_v10_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_lmb_bram_1/sim/base_lmb_bram_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_lmb_bram_if_cntlr_1/sim/base_lmb_bram_if_cntlr_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_logic_1_1/sim/base_logic_1_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_mb_1/sim/base_mb_1.vhd" \
    "$ref_dir/../../../bd/base/ip/base_mb_bram_ctrl_1/sim/base_mb_bram_ctrl_1.vhd" \
    "$ref_dir/../../../bd/base/ip/base_rst_clk_wiz_1_100M_1/sim/base_rst_clk_wiz_1_100M_1.vhd" \
    "$ref_dir/../../../bd/base/ip/base_spi_0/sim/base_spi_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_timer_6/sim/base_timer_6.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_dff_en_reset_vector_0_2/sim/base_dff_en_reset_vector_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_gpio_1/sim/base_gpio_1.vhd" \
    "$ref_dir/../../../bd/base/ip/base_iic_1/sim/base_iic_1.vhd" \
    "$ref_dir/../../../bd/base/ip/base_intc_2/sim/base_intc_2.vhd" \
    "$ref_dir/../../../bd/base/ip/base_intr_2/sim/base_intr_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_intr_concat_1/sim/base_intr_concat_1.v" \
    "$ref_dir/../../../bd/base/ip/base_io_switch_2/sim/base_io_switch_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_dlmb_v10_2/sim/base_dlmb_v10_2.vhd" \
    "$ref_dir/../../../bd/base/ip/base_ilmb_v10_2/sim/base_ilmb_v10_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_lmb_bram_2/sim/base_lmb_bram_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_lmb_bram_if_cntlr_2/sim/base_lmb_bram_if_cntlr_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_logic_1_2/sim/base_logic_1_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_mb_2/sim/base_mb_2.vhd" \
    "$ref_dir/../../../bd/base/ip/base_mb_bram_ctrl_2/sim/base_mb_bram_ctrl_2.vhd" \
    "$ref_dir/../../../bd/base/ip/base_rst_clk_wiz_1_100M_2/sim/base_rst_clk_wiz_1_100M_2.vhd" \
    "$ref_dir/../../../bd/base/ip/base_spi_1/sim/base_spi_1.vhd" \
    "$ref_dir/../../../bd/base/ip/base_timer_7/sim/base_timer_7.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_dff_en_reset_vector_0_3/sim/base_dff_en_reset_vector_0_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_iic_0_0/sim/base_iic_0_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_iic_1_0/sim/base_iic_1_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_intc_3/sim/base_intc_3.vhd" \
    "$ref_dir/../../../bd/base/ip/base_intr_3/sim/base_intr_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_intr_concat_2/sim/base_intr_concat_2.v" \
    "$ref_dir/../../../bd/base/ip/base_io_switch_3/sim/base_io_switch_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_dlmb_v10_3/sim/base_dlmb_v10_3.vhd" \
    "$ref_dir/../../../bd/base/ip/base_ilmb_v10_3/sim/base_ilmb_v10_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_lmb_bram_3/sim/base_lmb_bram_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_lmb_bram_if_cntlr_3/sim/base_lmb_bram_if_cntlr_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_logic_1_3/sim/base_logic_1_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_mb_3/sim/base_mb_3.vhd" \
    "$ref_dir/../../../bd/base/ip/base_mb_bram_ctrl_3/sim/base_mb_bram_ctrl_3.vhd" \
    "$ref_dir/../../../bd/base/ip/base_rpi_gpio_0/sim/base_rpi_gpio_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_rst_clk_wiz_1_100M_3/sim/base_rst_clk_wiz_1_100M_3.vhd" \
    "$ref_dir/../../../bd/base/ip/base_spi_0_0/sim/base_spi_0_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_spi_1_0/sim/base_spi_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_mb4_timer_pwm_0/sim/base_mb4_timer_pwm_0.v" \
    "$ref_dir/../../../bd/base/ip/base_mb4_timers_interrupt_0/sim/base_mb4_timers_interrupt_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_timer_0_1/sim/base_timer_0_1.vhd" \
    "$ref_dir/../../../bd/base/ip/base_timer_1_1/sim/base_timer_1_1.vhd" \
    "$ref_dir/../../../bd/base/ip/base_uartlite_1/sim/base_uartlite_1.vhd" \
    "$ref_dir/../../../bd/base/ip/base_leds_gpio_0/sim/base_leds_gpio_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_logic_1_4/sim/base_logic_1_4.v" \
    "$ref_dir/../../../bd/base/ip/base_mb_iop_arduino_intr_ack_0/sim/base_mb_iop_arduino_intr_ack_0.v" \
    "$ref_dir/../../../bd/base/ip/base_mb_iop_arduino_reset_0/sim/base_mb_iop_arduino_reset_0.v" \
    "$ref_dir/../../../bd/base/ip/base_mb_iop_pmoda_intr_ack_0/sim/base_mb_iop_pmoda_intr_ack_0.v" \
    "$ref_dir/../../../bd/base/ip/base_mb_iop_pmoda_reset_0/sim/base_mb_iop_pmoda_reset_0.v" \
    "$ref_dir/../../../bd/base/ip/base_mb_iop_pmodb_intr_ack_0/sim/base_mb_iop_pmodb_intr_ack_0.v" \
    "$ref_dir/../../../bd/base/ip/base_mb_iop_pmodb_reset_0/sim/base_mb_iop_pmodb_reset_0.v" \
    "$ref_dir/../../../bd/base/ip/base_mb_iop_rpi_intr_ack_0/sim/base_mb_iop_rpi_intr_ack_0.v" \
    "$ref_dir/../../../bd/base/ip/base_mb_iop_rpi_reset_0/sim/base_mb_iop_rpi_reset_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work mdm_v3_2_18 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/e9fa/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_mdm_1_0/sim/base_mdm_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_pmoda_rp_pin_sel_0/sim/base_pmoda_rp_pin_sel_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ce6c/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_9 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_ps7_0_0/sim/base_ps7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_rgbleds_gpio_0/sim/base_rgbleds_gpio_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_rst_ps7_0_fclk0_0/sim/base_rst_ps7_0_fclk0_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_rst_ps7_0_fclk1_0/sim/base_rst_ps7_0_fclk1_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_rst_ps7_0_fclk3_0/sim/base_rst_ps7_0_fclk3_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ipshared/7bdd/interface_slice.v" \
    "$ref_dir/../../../bd/base/ip/base_slice_pmodb_gpio_0/sim/base_slice_pmodb_gpio_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_switches_gpio_0/sim/base_switches_gpio_0.vhd" \
    "$ref_dir/../../../bd/base/ip/base_system_interrupts_0/sim/base_system_interrupts_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_23 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/af86/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_13 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/4919/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_22 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/0fb1/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_axi_dma_0_0/sim/base_axi_dma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_data_fifo_v2_0_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/50d0/hdl/axis_data_fifo_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_axis_data_fifo_0_0/sim/base_axis_data_fifo_0_0.v" \
    "$ref_dir/../../../bd/base/ip/base_constant_tkeep_tstrb_0/sim/base_constant_tkeep_tstrb_0.v" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/06c0/hdl/verilog/regslice_core.v" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/06c0/hdl/verilog/trace_cntrl_64_trace_cntrl_s_axi.v" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/06c0/hdl/verilog/trace_cntrl_64.v" \
    "$ref_dir/../../../bd/base/ip/base_trace_cntrl_64_0_0/sim/base_trace_cntrl_64_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_axi_dma_0_1/sim/base_axi_dma_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_axis_data_fifo_0_1/sim/base_axis_data_fifo_0_1.v" \
    "$ref_dir/../../../bd/base/ip/base_constant_tkeep_tstrb_1/sim/base_constant_tkeep_tstrb_1.v" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/21ac/hdl/verilog/trace_cntrl_32_trace_cntrl_s_axi.v" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/21ac/hdl/verilog/trace_cntrl_32.v" \
    "$ref_dir/../../../bd/base/ip/base_trace_cntrl_32_0_0/sim/base_trace_cntrl_32_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_13 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/af67/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_9 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_axi_vdma_0/sim/base_axi_vdma_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_register_slice_v1_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7da1/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_axis_register_slice_0_0/sim/base_axis_register_slice_0_0.v" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/57ab/hdl/verilog/color_convert_AXILiteS_s_axi.v" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/57ab/hdl/verilog/color_convert_macbkb.v" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/57ab/hdl/verilog/color_convert_maccud.v" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/57ab/hdl/verilog/color_convert.v" \
    "$ref_dir/../../../bd/base/ip/base_color_convert_0/sim/base_color_convert_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_axi_gpio_hdmiin_0/sim/base_axi_gpio_hdmiin_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ipshared/4b6f/color_swap.v" \
    "$ref_dir/../../../bd/base/ip/base_color_swap_0_0/sim/base_color_swap_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/269e/src/SyncBase.vhd" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/269e/src/EEPROM_8b.vhd" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/269e/src/TWI_SlaveCtl.vhd" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/269e/src/GlitchFilter.vhd" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/269e/src/SyncAsync.vhd" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/269e/src/DVI_Constants.vhd" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/269e/src/SyncAsyncReset.vhd" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/269e/src/PhaseAlign.vhd" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/269e/src/InputSERDES.vhd" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/269e/src/ChannelBond.vhd" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/269e/src/ResyncToBUFG.vhd" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/269e/src/TMDS_Decoder.vhd" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/269e/src/TMDS_Clocking.vhd" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/269e/src/dvi2rgb.vhd" \
    "$ref_dir/../../../bd/base/ip/base_dvi2rgb_0_0/sim/base_dvi2rgb_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/b2aa/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_v_vid_in_axi4s_0_0/sim/base_v_vid_in_axi4s_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work v_tc_v6_2_0 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/111e/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_vtc_in_0/sim/base_vtc_in_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/9076/hdl/verilog/pixel_pack_AXILiteS_s_axi.v" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/9076/hdl/verilog/pixel_pack.v" \
    "$ref_dir/../../../bd/base/ip/base_pixel_pack_0/sim/base_pixel_pack_0.v" \
    "$ref_dir/../../../bd/base/ip/base_axis_register_slice_0_1/sim/base_axis_register_slice_0_1.v" \
    "$ref_dir/../../../bd/base/ip/base_color_convert_1/sim/base_color_convert_1.v" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/9097/src/mmcme2_drp.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/9097/src/axi_dynclk_S00_AXI.vhd" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/9097/src/axi_dynclk.vhd" \
    "$ref_dir/../../../bd/base/ip/base_axi_dynclk_0/sim/base_axi_dynclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_color_swap_0_1/sim/base_color_swap_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_hdmi_out_hpd_video_0/sim/base_hdmi_out_hpd_video_0.vhd" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/bd5a/src/ClockGen.vhd" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/bd5a/src/OutputSERDES.vhd" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/bd5a/src/TMDS_Encoder.vhd" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/bd5a/src/rgb2dvi.vhd" \
    "$ref_dir/../../../bd/base/ip/base_rgb2dvi_0_0/sim/base_rgb2dvi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_13 $vhdlan_opts \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_axi4s_vid_out_v4_0_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/a87e/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_v_axi4s_vid_out_0_0/sim/base_v_axi4s_vid_out_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_vtc_out_0/sim/base_vtc_out_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/bba3/hdl/verilog/pixel_unpack_AXILiteS_s_axi.v" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/bba3/hdl/verilog/pixel_unpack.v" \
    "$ref_dir/../../../bd/base/ip/base_pixel_unpack_0/sim/base_pixel_unpack_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/base/ip/base_proc_sys_reset_pixelclk_0/sim/base_proc_sys_reset_pixelclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_xlconcat_0_0/sim/base_xlconcat_0_0.v" \
    "$ref_dir/../../../bd/base/ipshared/1a70/wire_distributor.v" \
    "$ref_dir/../../../bd/base/ip/base_collector_pmoda_rpi_0/sim/base_collector_pmoda_rpi_0.v" \
    "$ref_dir/../../../bd/base/ip/base_collector_rpi_27_8_0/sim/base_collector_rpi_27_8_0.v" \
    "$ref_dir/../../../bd/base/ip/base_distributor_pmoda_0/sim/base_distributor_pmoda_0.v" \
    "$ref_dir/../../../bd/base/ip/base_distributor_rpi_0/sim/base_distributor_rpi_0.v" \
    "$ref_dir/../../../bd/base/ipshared/8ae7/mux_vector.v" \
    "$ref_dir/../../../bd/base/ip/base_pmoda_rpi_o_sel_0/sim/base_pmoda_rpi_o_sel_0.v" \
    "$ref_dir/../../../bd/base/ip/base_pmoda_rpi_t_sel_0/sim/base_pmoda_rpi_t_sel_0.v" \
    "$ref_dir/../../../bd/base/ip/base_rpi_i_27_0_0/sim/base_rpi_i_27_0_0.v" \
    "$ref_dir/../../../bd/base/ip/base_pmoda_rpi_1_0_0/sim/base_pmoda_rpi_1_0_0.v" \
    "$ref_dir/../../../bd/base/ip/base_pmoda_rpi_3_2_0/sim/base_pmoda_rpi_3_2_0.v" \
    "$ref_dir/../../../bd/base/ip/base_pmoda_rpi_5_4_0/sim/base_pmoda_rpi_5_4_0.v" \
    "$ref_dir/../../../bd/base/ip/base_pmoda_rpi_7_6_0/sim/base_pmoda_rpi_7_6_0.v" \
    "$ref_dir/../../../bd/base/ip/base_rpi2pmoda_0/sim/base_rpi2pmoda_0.v" \
    "$ref_dir/../../../bd/base/ip/base_rpi_o_27_8_0/sim/base_rpi_o_27_8_0.v" \
    "$ref_dir/../../../bd/base/ip/base_rpi2pmoda_1/sim/base_rpi2pmoda_1.v" \
    "$ref_dir/../../../bd/base/ip/base_rpi_1_0_0/sim/base_rpi_1_0_0.v" \
    "$ref_dir/../../../bd/base/ip/base_rpi_3_2_0/sim/base_rpi_3_2_0.v" \
    "$ref_dir/../../../bd/base/ip/base_rpi_5_4_0/sim/base_rpi_5_4_0.v" \
    "$ref_dir/../../../bd/base/ip/base_rpi_7_6_0/sim/base_rpi_7_6_0.v" \
    "$ref_dir/../../../bd/base/ip/base_rpi_t_27_8_0/sim/base_rpi_t_27_8_0.v" \
    "$ref_dir/../../../bd/base/ip/base_rpi2pmoda_2/sim/base_rpi2pmoda_2.v" \
    "$ref_dir/../../../bd/base/ip/base_rpi_1_0_1/sim/base_rpi_1_0_1.v" \
    "$ref_dir/../../../bd/base/ip/base_rpi_3_2_1/sim/base_rpi_3_2_1.v" \
    "$ref_dir/../../../bd/base/ip/base_rpi_5_4_1/sim/base_rpi_5_4_1.v" \
    "$ref_dir/../../../bd/base/ip/base_rpi_7_6_1/sim/base_rpi_7_6_1.v" \
    "$ref_dir/../../../bd/base/ip/base_xlconcat_0_1/sim/base_xlconcat_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/2ef9/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/47c9/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/b68e/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_xbar_15/sim/base_xbar_15.v" \
    "$ref_dir/../../../bd/base/ip/base_xbar_16/sim/base_xbar_16.v" \
    "$ref_dir/../../../bd/base/ip/base_xbar_17/sim/base_xbar_17.v" \
    "$ref_dir/../../../bd/base/ip/base_xbar_18/sim/base_xbar_18.v" \
    "$ref_dir/../../../bd/base/ip/base_xbar_12/sim/base_xbar_12.v" \
    "$ref_dir/../../../bd/base/ip/base_xbar_14/sim/base_xbar_14.v" \
    "$ref_dir/../../../bd/base/ip/base_xbar_11/sim/base_xbar_11.v" \
    "$ref_dir/../../../bd/base/ip/base_xbar_13/sim/base_xbar_13.v" \
    "$ref_dir/../../../bd/base/ip/base_xbar_19/sim/base_xbar_19.v" \
    "$ref_dir/../../../bd/base/ip/base_xbar_20/sim/base_xbar_20.v" \
    "$ref_dir/../../../bd/base/ip/base_xbar_21/sim/base_xbar_21.v" \
    "$ref_dir/../../../bd/base/ip/base_tier2_xbar_0_0/sim/base_tier2_xbar_0_0.v" \
    "$ref_dir/../../../bd/base/ip/base_tier2_xbar_1_0/sim/base_tier2_xbar_1_0.v" \
    "$ref_dir/../../../bd/base/ip/base_tier2_xbar_2_0/sim/base_tier2_xbar_2_0.v" \
    "$ref_dir/../../../bd/base/ip/base_s00_regslice_16/sim/base_s00_regslice_16.v" \
    "$ref_dir/../../../bd/base/ip/base_m00_regslice_16/sim/base_m00_regslice_16.v" \
    "$ref_dir/../../../bd/base/ip/base_m01_regslice_16/sim/base_m01_regslice_16.v" \
    "$ref_dir/../../../bd/base/ip/base_m02_regslice_16/sim/base_m02_regslice_16.v" \
    "$ref_dir/../../../bd/base/ip/base_m03_regslice_16/sim/base_m03_regslice_16.v" \
    "$ref_dir/../../../bd/base/ip/base_m04_regslice_12/sim/base_m04_regslice_12.v" \
    "$ref_dir/../../../bd/base/ip/base_m05_regslice_12/sim/base_m05_regslice_12.v" \
    "$ref_dir/../../../bd/base/ip/base_m06_regslice_12/sim/base_m06_regslice_12.v" \
    "$ref_dir/../../../bd/base/ip/base_m07_regslice_12/sim/base_m07_regslice_12.v" \
    "$ref_dir/../../../bd/base/ip/base_m08_regslice_6/sim/base_m08_regslice_6.v" \
    "$ref_dir/../../../bd/base/ip/base_m09_regslice_6/sim/base_m09_regslice_6.v" \
    "$ref_dir/../../../bd/base/ip/base_m10_regslice_4/sim/base_m10_regslice_4.v" \
    "$ref_dir/../../../bd/base/ip/base_m11_regslice_4/sim/base_m11_regslice_4.v" \
    "$ref_dir/../../../bd/base/ip/base_m12_regslice_0/sim/base_m12_regslice_0.v" \
    "$ref_dir/../../../bd/base/ip/base_m13_regslice_0/sim/base_m13_regslice_0.v" \
    "$ref_dir/../../../bd/base/ip/base_m14_regslice_0/sim/base_m14_regslice_0.v" \
    "$ref_dir/../../../bd/base/ip/base_m15_regslice_0/sim/base_m15_regslice_0.v" \
    "$ref_dir/../../../bd/base/ip/base_m16_regslice_0/sim/base_m16_regslice_0.v" \
    "$ref_dir/../../../bd/base/ip/base_s00_regslice_17/sim/base_s00_regslice_17.v" \
    "$ref_dir/../../../bd/base/ip/base_m00_regslice_17/sim/base_m00_regslice_17.v" \
    "$ref_dir/../../../bd/base/ip/base_m01_regslice_17/sim/base_m01_regslice_17.v" \
    "$ref_dir/../../../bd/base/ip/base_m02_regslice_17/sim/base_m02_regslice_17.v" \
    "$ref_dir/../../../bd/base/ip/base_m03_regslice_17/sim/base_m03_regslice_17.v" \
    "$ref_dir/../../../bd/base/ip/base_m04_regslice_13/sim/base_m04_regslice_13.v" \
    "$ref_dir/../../../bd/base/ip/base_m05_regslice_13/sim/base_m05_regslice_13.v" \
    "$ref_dir/../../../bd/base/ip/base_m06_regslice_13/sim/base_m06_regslice_13.v" \
    "$ref_dir/../../../bd/base/ip/base_m07_regslice_13/sim/base_m07_regslice_13.v" \
    "$ref_dir/../../../bd/base/ip/base_s00_regslice_18/sim/base_s00_regslice_18.v" \
    "$ref_dir/../../../bd/base/ip/base_m00_regslice_18/sim/base_m00_regslice_18.v" \
    "$ref_dir/../../../bd/base/ip/base_m01_regslice_18/sim/base_m01_regslice_18.v" \
    "$ref_dir/../../../bd/base/ip/base_m02_regslice_18/sim/base_m02_regslice_18.v" \
    "$ref_dir/../../../bd/base/ip/base_m03_regslice_18/sim/base_m03_regslice_18.v" \
    "$ref_dir/../../../bd/base/ip/base_m04_regslice_14/sim/base_m04_regslice_14.v" \
    "$ref_dir/../../../bd/base/ip/base_m05_regslice_14/sim/base_m05_regslice_14.v" \
    "$ref_dir/../../../bd/base/ip/base_m06_regslice_14/sim/base_m06_regslice_14.v" \
    "$ref_dir/../../../bd/base/ip/base_m07_regslice_14/sim/base_m07_regslice_14.v" \
    "$ref_dir/../../../bd/base/ip/base_s00_regslice_19/sim/base_s00_regslice_19.v" \
    "$ref_dir/../../../bd/base/ip/base_m00_regslice_19/sim/base_m00_regslice_19.v" \
    "$ref_dir/../../../bd/base/ip/base_m01_regslice_19/sim/base_m01_regslice_19.v" \
    "$ref_dir/../../../bd/base/ip/base_m02_regslice_19/sim/base_m02_regslice_19.v" \
    "$ref_dir/../../../bd/base/ip/base_m03_regslice_19/sim/base_m03_regslice_19.v" \
    "$ref_dir/../../../bd/base/ip/base_m04_regslice_15/sim/base_m04_regslice_15.v" \
    "$ref_dir/../../../bd/base/ip/base_m05_regslice_15/sim/base_m05_regslice_15.v" \
    "$ref_dir/../../../bd/base/ip/base_m06_regslice_15/sim/base_m06_regslice_15.v" \
    "$ref_dir/../../../bd/base/ip/base_m07_regslice_15/sim/base_m07_regslice_15.v" \
    "$ref_dir/../../../bd/base/ip/base_m08_regslice_7/sim/base_m08_regslice_7.v" \
    "$ref_dir/../../../bd/base/ip/base_m09_regslice_7/sim/base_m09_regslice_7.v" \
    "$ref_dir/../../../bd/base/ip/base_m10_regslice_5/sim/base_m10_regslice_5.v" \
    "$ref_dir/../../../bd/base/ip/base_m11_regslice_5/sim/base_m11_regslice_5.v" \
    "$ref_dir/../../../bd/base/ip/base_s00_regslice_20/sim/base_s00_regslice_20.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8dfa/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_auto_pc_0/sim/base_auto_pc_0.v" \
    "$ref_dir/../../../bd/base/ip/base_m00_regslice_20/sim/base_m00_regslice_20.v" \
    "$ref_dir/../../../bd/base/ip/base_m01_regslice_20/sim/base_m01_regslice_20.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7589/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_auto_cc_0/sim/base_auto_cc_0.v" \
    "$ref_dir/../../../bd/base/ip/base_m02_regslice_20/sim/base_m02_regslice_20.v" \
    "$ref_dir/../../../bd/base/ip/base_auto_cc_1/sim/base_auto_cc_1.v" \
    "$ref_dir/../../../bd/base/ip/base_m03_regslice_20/sim/base_m03_regslice_20.v" \
    "$ref_dir/../../../bd/base/ip/base_m04_regslice_16/sim/base_m04_regslice_16.v" \
    "$ref_dir/../../../bd/base/ip/base_m05_regslice_16/sim/base_m05_regslice_16.v" \
    "$ref_dir/../../../bd/base/ip/base_m06_regslice_16/sim/base_m06_regslice_16.v" \
    "$ref_dir/../../../bd/base/ip/base_auto_cc_2/sim/base_auto_cc_2.v" \
    "$ref_dir/../../../bd/base/ip/base_m07_regslice_16/sim/base_m07_regslice_16.v" \
    "$ref_dir/../../../bd/base/ip/base_auto_cc_3/sim/base_auto_cc_3.v" \
    "$ref_dir/../../../bd/base/ip/base_m08_regslice_8/sim/base_m08_regslice_8.v" \
    "$ref_dir/../../../bd/base/ip/base_m09_regslice_8/sim/base_m09_regslice_8.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/07be/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8b3d" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../base_hdmi.srcs/sources_1/bd/base/ipshared/7af1/hdl" +incdir+"C:/Xilinx/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/base/ip/base_auto_us_0/sim/base_auto_us_0.v" \
    "$ref_dir/../../../bd/base/ip/base_auto_pc_1/sim/base_auto_pc_1.v" \
    "$ref_dir/../../../bd/base/ip/base_auto_pc_2/sim/base_auto_pc_2.v" \
    "$ref_dir/../../../bd/base/ip/base_auto_us_1/sim/base_auto_us_1.v" \
    "$ref_dir/../../../bd/base/ip/base_auto_pc_3/sim/base_auto_pc_3.v" \
    "$ref_dir/../../../bd/base/ip/base_s00_regslice_14/sim/base_s00_regslice_14.v" \
    "$ref_dir/../../../bd/base/ip/base_m00_regslice_14/sim/base_m00_regslice_14.v" \
    "$ref_dir/../../../bd/base/ip/base_m01_regslice_14/sim/base_m01_regslice_14.v" \
    "$ref_dir/../../../bd/base/ip/base_m02_regslice_14/sim/base_m02_regslice_14.v" \
    "$ref_dir/../../../bd/base/ip/base_m03_regslice_14/sim/base_m03_regslice_14.v" \
    "$ref_dir/../../../bd/base/ip/base_s00_regslice_15/sim/base_s00_regslice_15.v" \
    "$ref_dir/../../../bd/base/ip/base_auto_pc_10/sim/base_auto_pc_10.v" \
    "$ref_dir/../../../bd/base/ip/base_m00_regslice_15/sim/base_m00_regslice_15.v" \
    "$ref_dir/../../../bd/base/ip/base_auto_pc_4/sim/base_auto_pc_4.v" \
    "$ref_dir/../../../bd/base/ip/base_m01_regslice_15/sim/base_m01_regslice_15.v" \
    "$ref_dir/../../../bd/base/ip/base_m02_regslice_15/sim/base_m02_regslice_15.v" \
    "$ref_dir/../../../bd/base/ip/base_auto_pc_5/sim/base_auto_pc_5.v" \
    "$ref_dir/../../../bd/base/ip/base_m03_regslice_15/sim/base_m03_regslice_15.v" \
    "$ref_dir/../../../bd/base/ip/base_auto_pc_6/sim/base_auto_pc_6.v" \
    "$ref_dir/../../../bd/base/ip/base_m04_regslice_11/sim/base_m04_regslice_11.v" \
    "$ref_dir/../../../bd/base/ip/base_auto_pc_7/sim/base_auto_pc_7.v" \
    "$ref_dir/../../../bd/base/ip/base_m05_regslice_11/sim/base_m05_regslice_11.v" \
    "$ref_dir/../../../bd/base/ip/base_auto_pc_8/sim/base_auto_pc_8.v" \
    "$ref_dir/../../../bd/base/ip/base_m06_regslice_11/sim/base_m06_regslice_11.v" \
    "$ref_dir/../../../bd/base/ip/base_m07_regslice_11/sim/base_m07_regslice_11.v" \
    "$ref_dir/../../../bd/base/ip/base_auto_pc_9/sim/base_auto_pc_9.v" \
    "$ref_dir/../../../bd/base/ip/base_auto_pc_11/sim/base_auto_pc_11.v" \
    "$ref_dir/../../../bd/base/sim/base.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.base xil_defaultlib.glbl -o base_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./base_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./base.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key base_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc base_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./base.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: base.sh [-help]\n\
Usage: base.sh [-lib_map_path]\n\
Usage: base.sh [-reset_run]\n\
Usage: base.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
